### PR TITLE
Add kanuti (tulip) projects

### PR DESCRIPTION
**Pull request by pablomh**
It seems that they were not added (was it on purpose?).

### CODE REVIEW

**Comment by AdFad666** [comment]
Hi, Thanks for the PR! Does tulip really build successfully and boot successfully using the AOSP device repos and the kernel found here on Contortrix?

**Comment by pablomh** [comment]
Not really at the moment :(

I'm trying to port what I found while building using @alviteri SonyAOSP repo and I'm still having some problems. Apart from that my tulip is a tulip_dsds and I'm awaiting for the release of the .dts for it.

I can understand if you prefer until I confirm that it boots with my fixes :)

**Comment by AdFad666** [comment]
OK, it's still as I suspected. Not booting is the reason I didn't include tulip. If you make progress please let me know, I have a tulip so I can also test CopperheadOS on it, but I don't have enough time to chase down the not booting reasons :disappointed:

**Comment by boylush** [comment]
@pablomh would it be possible to discuss about trying to boot M4? We have a dev group on telegram with a few other M4 devs, do drop me a hangout at renjie351@gmail.com or telegram @boylush, thanks!

**Comment by pablomh** [comment]
Did you drop it in your rebase? :S

**Comment by AdFad666** [comment]
Sorry this got closed automatically when I rebased :fearful:

**Comment by pablomh** [comment]
Do you want me to redo it?

**Pull request closed without merging**
