### PR TITLE
Add kanuti (tulip) projects

### PR DESCRIPTION
**Pull request by pablomh**
Try #2

### CODE REVIEW

**Comment by pablomh** [comment]
Can you try again to rebase with this?

**Comment by AdFad666** [comment]
Is it booting now?

**Comment by pablomh** [comment]
No. I want to have all the scaffolding ready to be able to test once the underlying issue (IOMMU??) is fixed and it boots.

**Comment by AdFad666** [comment]
auto closed again due to branches. I saw some tulip activity at Sony, does it help?

**Comment by pablomh** [comment]
It helped in making the tree buildable but it doesn't boot yet.

I'm trying to get some time to try to see if I get any log/info from the boot or maybe I'll just wait for 3.18 to land...

**Pull request closed without merging**
